ChiBurger/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextField
from wtforms.validators import DataRequired, Email, Length, Regexp, EqualTo
from wtforms import ValidationError

from ..models import Article


class ArticleForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(message='must add a title'), Length(1,64)])
    body = TextField('Body', validators=[DataRequired()])
    submit = SubmitField()

ChiBurger/main/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, Length, Regexp, EqualTo
from wtforms import ValidationError

from ..models import User

class LoginForm(FlaskForm):
    email = StringField(u'邮箱', validators=[DataRequired(message='a email is needed'), Email()])
    password = PasswordField(u'密码', validators=[DataRequired(message='must enter a password')])
    submit = SubmitField(u'登录')


class SignupForm(FlaskForm):
    username = StringField(u'用户名',validators=[DataRequired(message='a username is needed.'), Length(1,64)])
    email = StringField(u'邮箱',validators=[DataRequired(message='a email is needed'),Length(1,64), Email()])
    password = PasswordField(u'密码', validators=[DataRequired(message='must enter a password'), EqualTo('confirm', message='Password must match')])
    confirm = PasswordField(u'确认密码', validators=[DataRequired()])
    submit = SubmitField(u'注册')

    def validate_username(form, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')

    def vaidate_email(form, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

ChiBurger/__init__.py
# -*- coding:utf-8 -*-

from flask import Flask

from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_uploads import UploadSet, IMAGES, configure_uploads

from config import config

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'main.login'
bootstrap = Bootstrap()
moment = Moment()

# 上传图片
photos = UploadSet('photos', IMAGES)


def create_app(config_name):
    # initialize app
    app = Flask(__name__, instance_relative_config=True)

    # import config
    app.config.from_object(config[config_name])
    app.config.from_pyfile('config.py')

    # 上传图片位置
    import os
    basebir = os.path.abspath(os.path.dirname(__file__))
    app.config['UPLOADED_PHOTOS_DEST'] = basebir + '/static/img'

    # flask extensions initial
    db.init_app(app)
    # toolbar.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)
    configure_uploads(app, photos)

    # import blueprint
    from .admin import admin as admin_blueprint
    from .blog import blog as blog_blueprint
    from .main import main as main_blueprint
    from .profile import profile as profile_blueprint
    from .api_1_0 import api as api_1_0_blueprint

    # register blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')
    app.register_blueprint(blog_blueprint, url_prefix='/blog')
    app.register_blueprint(profile_blueprint, url_prefix='/profile')
    app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')
    app.register_blueprint(main_blueprint)

    return app

ChiBurger/admin/__init__.py
# -*- coding:utf-8 -*-

from flask import Blueprint

# create blueprint: admin
admin = Blueprint('admin', __name__)

# after admin blueprint created, import views
from . import views

ChiBurger/admin/views.py
# -*- coding:utf-8 -*-

from .articles import *
from .categories import *

@admin.route('/')
def index():
    return render_template('admin/index.html')

# 404错误处理
@admin.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

# 500错误处理
@admin.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

ChiBurger/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import  views

ChiBurger/api_1_0/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

ChiBurger/blog/__init__.py
# -*- coding:utf-8 -*-

from flask import Blueprint

# create blueprint:blog
blog = Blueprint('blog', __name__)

# after blueprint created, import views
from . import views

ChiBurger/blog/views.py
# -*- coding:utf-8 -*-

from flask import render_template, url_for, abort, redirect, flash, request, jsonify, Response
from flask_login import login_user, logout_user, login_required, user_login_confirmed

from . import blog
from .. import db, moment
from ..models import Article, User, Category, Comment
from .forms import ArticleForm
from ..utils import get_json_articleInfo, add_category


# blog首页展示所有文章
@blog.route('/')
def index():
    articles = Article.query.order_by(Article.pub_time.desc()).all()
    return render_template('blog/index.html', articles=articles)


# 文章归档
@blog.route('/articles')
def articles():
    articles = Article.query.order_by(Article.pub_time.desc()).all()
    article_num = Article.query.count()
    return render_template('blog/articles.html', 
                            articles=articles, 
                            article_num=article_num)

# 返回指定id的文章
@blog.route('/article/<int:id>')
def article(id):
    article = Article.query.get_or_404(id)
    comments = article.comments.order_by(Comment.pub_time.desc()).all()
    return render_template('blog/article.html', 
                            article=article, 
                            comments=comments)


# 增加新的文章
@blog.route('/article/add', methods=['GET','POST'])
@login_required
def addArticle():
    if request.method == 'POST':
        form = request.form
        title = form.get('title')
        category_name = form.get('category')
        category = add_category(name=category_name)
        body = form.get('editormd-html-code')
        body_md = form.get('editormd-markdown-doc')
        article = Article(title=title, category_id=category.id,
                            body=body, body_md=body_md, user_id=current_user.id)
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('blog.article', id=article.id))
    return render_template('blog/add_article.html')


# 修改指定id的文章
@blog.route('/article/<int:id>/edit', methods=['GET','POST'])
@login_required
def editArticle(id):
    article = Article.query.get_or_404(id)
    if request.method == 'POST':
        form = request.form
        article.title = form.get('title')
        category_name = form.get('category')
        category = add_category(name=category_name)
        article.category_id = category.id
        article.body = form.get('editormd-html-code')
        article.body_md = form.get('editormd-markdown-doc')
        article.mod_time = datetime.utcnow()
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('blog.article', id=id))
    return render_template('blog/edit_article.html', article=article)


# 删除指定id的文章
@blog.route('/article/<int:id>/delete')
@login_required
def deleteArticle(id):
    article = Article.query.get_or_404(id)
    db.session.delete(article)
    db.session.commit()
    return jsonify(status='success')


# 返回所有的文章分类
@blog.route('/categories')
def categories():
    categories = Category.query.all()
    category_num = Category.query.count()
    return render_template('blog/categories.html', 
                            categories=categories,
                            category_num=category_num)

# 返回指定id的文章分类
@blog.route('/category/<int:id>')
def category(id):
    category = Category.query.get_or_404(id)
    articles = category.articles.all()
    article_num = category.articles.count()
    return render_template('blog/category.html', 
                            category=category, 
                            articles=articles, 
                            article_num=article_num)


# 增加新的分类
@blog.route('/category/add', methods=['POST'])
# @login_required
def addCategory():
    form = request.form
    name = form.get('category-name')
    category = Category.query.filter_by(name=name).first()
    if category:
        return jsonify(status='fail', error='The category already exists.')
    category = Category(name=name)
    db.session.add(category)
    db.session.commit()
    return jsonify(status='success')


# 更新指定id的分类信息
@blog.route('/category/<int:id>/edit', methods=['POST'])
@login_required
def editCategory(id):
    category = Category.query.get_or_404(id)
    form = request.form
    category.name = form.get('category-name')
    db.session.add(category)
    db.session.commit()
    return jsonify(status='success')


# 删除指定id的分类
@blog.route('/category/<int:id>/delete', methods=['POST'])
@login_required
def deleteCategory(id):
    category = Category.query.get_or_404(id)
    db.session.delete(category)
    db.session.commit()
    return jsonify(status='success')


# 增加评论
@blog.route('/article/<int:id>/add_comments', methods=['GET', 'POST'])
def addComments(id):
    article = Article.query.get_or_404(id)
    if article:
        comments = article.comments.order_by(Comment.pub_time.desc()).all()
    if request.method == 'POST':
        body = request.form['body']
        user_ip = request.remote_addr
        user_platform = request.user_agent.platform
        user_browser = request.user_agent.browser
        article_id = id
        comment = Comment(body=body, article_id=article_id, user_ip=user_ip,
                            user_platform=user_platform, user_browser=user_browser)
        db.session.add(comment)
        db.session.commit()
        comment_num = article.comments.count()
        return jsonify(id=comment.id,body=comment.body,
                        pub_time=comment.pub_time,
                        article_id=comment.article_id,
                        user_ip=user_ip, 
                        user_platform=user_platform,
                        user_browser=user_browser,
                        comment_num=comment_num)

# 404错误处理
@blog.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

# 500错误处理
@blog.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

ChiBurger/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

ChiBurger/main/views.py
# -*- coding:utf-8 -*-

from flask import render_template, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required
from . import main
from .. import db
from ..models import User, Profile
from .forms import LoginForm, SignupForm

@main.route('/')
def index():
    return redirect(url_for('blog.index'))

@main.route('/login', methods=['GET','POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None:
            if user.vertify_password(form.password.data):
                login_user(user)
                flash("You have logined in successfully!")
                return redirect(request.args.get('next') or url_for('blog.index'))
            flash('Invalid password')
        else:
            flash('Invalid email')
    return render_template('login.html', form=form)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@main.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        user = User(username=form.username.data,
                    password=form.password.data,
                    email=form.email.data)
        profile = Profile(user_id=user.id)
        db.session.add(user)
        db.session.add(profile)
        db.session.commit()
        flash("You have signed up successfully. Now you can login in.")
        return redirect(url_for('main.login'))
    return render_template('signup.html', form=form)

ChiBurger/profile/__init__.py
from flask import Blueprint

profile = Blueprint('profile', __name__)

from . import views

ChiBurger/profile/views.py
# -*- coding:utf-8 -*-

from flask import render_template, url_for, abort, redirect, request, jsonify
from flask_login import login_user, logout_user, login_required, user_login_confirmed, current_user
from flask_uploads import UploadNotAllowed

from . import profile
from .. import db, photos

from ..models import User, Article, Profile, Photo, Message
from ..utils import upload


@profile.route('/')
def index():
    return render_template('profile/home.html')

@profile.route('/<username>')
def home(username):
    user = User.query.filter_by(username=username).first_or_404()
    profile = user.profile
    messages_num = user.messages.count()
    page = request.args.get('page', 1, type=int)
    pagination = user.messages.order_by(Message.pub_time.desc()).paginate(page, per_page=10, error_out=False)
    messages = pagination.items
    return render_template('profile/index.html', user=user, profile=profile,
                            messages=messages, messages_num=messages_num, pagination=pagination)


@profile.route('/<username>/profile-detail')
def getProfile(username):
    user = User.query.filter_by(username=username).first_or_404()
    profile = user.profile
    if profile:
        profile = profile.to_json()
        return jsonify(status='success', profile=profile)
    return jsonify(status='fail', error="There's no profile for current user.")


@profile.route('/<username>/edit', methods=['GET', 'POST'])
@login_required
def editProfile(username):
    user = User.query.filter_by(username=username).first_or_404()
    profile = user.profile

    if request.method == 'POST':
        # import ipdb; ipdb.set_trace()
        if not profile:
            profile = Profile(user_id=user.id)

        # form表单提交
        # form = request.form
        # profile.nickname = form.get('nickname')
        # profile.gender = form.get('gender')
        # profile.address = form.get('address')
        # profile.discription = form.get('discription')

        # 前端Ajax提交
        request_items = request.values.keys()
        # 在模型字段中遍历请求中出现的字段，并且对其赋值
        # 只对修改的字段进行更新，其余未修改的字段不更新
        json_data = {}
        for item in request_items:
            request_value = request.values.get(item)
            setattr(profile, item, request_value)
            json_data[item] = getattr(profile, item)
        db.session.add(profile)
        db.session.commit()
        return jsonify(status='success', data=json_data)
    return render_template('profile/edit_profile.html', user=user, profile=profile)


@profile.route('/upload/avatar', methods=['POST'])
@login_required
def uploadAvatar():
    if request.method == 'POST' and 'photo' in request.files:
        photos = current_user.photos
        if photos is None or photos.filter_by(category='avatar').first() is None:
            avatar = Photo(category='avatar', user_id=current_user.id)
        else:
            avatar = photos.filter_by(category='avatar').first()
        url = upload(request.files['photo'])
        avatar.url = url
        current_user.avatar = url
        db.session.add(avatar)
        db.session.add(current_user)
        db.session.commit()

        return jsonify(status='success', url=url)
    return jsonify(status='fail')


@profile.route('/upload/cover', methods=['POST'])
@login_required
def uploadCover():
    profile = current_user.profile
    if profile is None:
        profile = Profile(user_id=current_user.id)
    if request.method == 'POST' and 'photo' in request.files:
        photos = current_user.photos
        if photos is None or photos.filter_by(category='cover').first() is None:
            cover = Photo(category='cover', user_id=current_user.id)
        else:
            cover = photos.filter_by(category='cover').first()
        url = upload(request.files['photo'])
        cover.url = url
        profile.cover = url
        db.session.add(cover)
        db.session.add(profile)
        db.session.commit()

        return jsonify(status='success', url=url)
    return jsonify(status='fail')


@profile.route('/<username>/add-activity', methods=['POST'])
@login_required
def addActivity(username):
    user = User.query.filter_by(username=username).first_or_404()
    profile = user.profile
    if request.method == 'POST':
        form = request.form
        body = form.get('body')
        message = Message(body=body,user_id=user.id)
        db.session.add(message)
        db.session.commit()
        return jsonify(status='success', message=message.to_json(),
                        user=user.to_json(), profile=profile.to_json())
    return jsonify(status='fail')


# 404错误处理
@profile.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

# 500错误处理
@profile.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

ChiBurger/templates/profile/index.html
{% extends 'base.html' %}

{% block title %} 个人主页 {% endblock %}

{% block head %}
{{super()}}
<script src="{{ url_for('static', filename='editormd/editormd.js') }}"></script>
<link rel="stylesheet" href="{{url_for('static', filename='editormd/css/editormd.css')}}" />
{% endblock %}

{% block content %}

{% import 'pagination_macros.html' as pagination_macros %}
{% import 'profile/profile_header.html' as profile_header %}
{{ profile_header.profile_header(profile, user, current_user) }}

<div class="profile-main">
    <div class="profile-mainColumn">
        <div class="card profileMain" id="profileMain">
            <!-- main page-header -->
            <div class="ProfileMain-header">
                <ul class=" Tabs ProfileMain-tabs">
                    <li class=" Tabs-item"><a class="Tabs-link" href="#profile" data-toggle="tab">个人简介</a></li>
                    <li class="active Tabs-item"><a class="Tabs-link" href="#activity" data-toggle="tab">动态</a></li>
                </ul>
            </div>

            <div class="tab-content" id="Profile-activities">
                <div class="List tab-pane fade " id="profile">
                    <div class="List-header">
                        <h4 class="List-headerText"><span>关于我</span></h4>
                        {% if current_user == user %}
                        <span><button id="edit-about">编辑</button></span>
                        {% endif %}
                    </div>
                    {% if profile is none or profile.about is none %}
                    <div class="EmptyState">
                        <div class="EmptyState-inner">
                            <div class="EmptyState-image"><i class="fa fa-file-text-o fa-3x"></i></div>
                            <span>还没有简介</span>
                            {% if current_user == user %}
                            <div><button id="about">点击添加</button></div>
                            {% endif %}
                        </div>
                    </div>
                    {% else %}
                    <div>
                        <div class="List-item">{{ profile.about | safe }}</div>
                    </div>
                    {% endif %}
                </div>
                <div class="List tab-pane fade in active" id="activity">
                    {% if current_user == user %}
                    <div class="activity">
                        <form id="addActivity" action="{{url_for('profile.addActivity', username=user.username)}}" method="post">
                            <textarea class="activity" name="body" placeholder="有什么新鲜事想要分享给大家"></textarea>
                            <!-- <button id="submitActivity" type="submit" class="btn btn-info">发布</button> -->
                        </form>
                        <button id="submitActivity" type="submit" class="btn btn-info">发布</button>
                    </div>
                    {% endif %}
                    <div class="List-header">
                        {% if current_user == user %}
                        <h4 class="List-headerText"><span>我的动态</span></h4>
                        {% else %}
                        <h4 class="List-headerText"><span>他的动态</span></h4>
                        {% endif %}
                    </div>
                    {% if messages_num == 0 %}
                    <div class="EmptyState">
                        <div class="EmptyState-inner">
                            <div class="EmptyState-image"><i class="fa fa-comments fa-3x"></i></div>
                            <span>还没有分享</span>
                        </div>
                    </div>
                    {% else %}
                    <div class="Activity-list">
                        {% for message in messages %}
                        <div class="Activity-item">
                            <div class="activity-content">
                                <div class="activity-user-avatar">
                                    {% if user.avatar is none %}
                                    <img src="{{ url_for('static', filename='anonymous.gif') }}">
                                    {% else %}
                                    <img src="{{ user.avatar }}">
                                    {% endif %}
                                </div>
                                <div class="activity-section">
                                    <div class="activity-user-info">
                                    {% if profile is none or profile.nickname is none %}
                                    {{user.username}}
                                    {% else %}
                                    {{profile.nickname}}
                                    {% endif %}
                                    </div>
                                    <div class="activity-text">
                                        <p class="comment">{{ message.body }}</p>
                                    </div>
                                    <div class="activity-handle activity-handle-btn">
                                        <span class="comment-timestamp">{{ moment(message.pub_time).fromNow() }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="pagination-item">
                    <div class="pagination">
                        {{pagination_macros.pagination_widget(pagination, 'profile.home', username=user.username)}}
                    </div>
                    </div>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{  super() }}
<script src="{{ url_for('static', filename='js/jquery.form.js') }}" ></script>
<script src="{{ url_for('static', filename='js/profile.js') }}" ></script>
<script>
    var username = '{{current_user.username }}' ;
</script>
{% endblock %}

ChiBurger/templates/profile/profile_header.html
{% macro profile_header(profile, user, current_user) -%}
<div id="profile-header" class="profileHeader">
    <div class="card">
        <div class="profileHeader-userCover">
            <div class="UserCoverEditor">
                <div class="UserCover">
                    {% if profile.cover is none %}
                    <img class="UserCover-image" src="{{ url_for('static', filename='img/cover.jpg') }}" alt="默认封面">
                    {% else %}
                    <img class="UserCover-image" src="{{ profile.cover }}" alt="用户封面">
                    {% endif %}
                </div>
                {% if current_user == user %}
                <button class="Button UserCoverEditor-simpleEditButton DynamicColorButton" type="button"><i class="fa fa-camera"> 上传封面图片</i></button>
                <form method="post" enctype="multipart/form-data" style="display: none;" action="{{ url_for('profile.uploadCover') }}">
                    <input type="file" name="photo" />
                </form>
                <div class="UserCoverEditor-action" style="display: none">
                    <div class="UserCoverEditor-actionContent">
                        <div><button class="Button Button--primary Button--blue" type="button">保存</button>
                        <button class="Button" type="button">取消</button>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="profileHeader-wrapper">
            <div class="profileHeader-main">
                <div class="userAvatarEditor profileHeader-avatar" style="top: -57px;">
                    <div class="UserAvatar">
                    {% if user.avatar is none %}
                    <img class="Avatar Avatar--large UserAvatar-inner" src="{{url_for('static', filename='img/avatar.png')}}" style="width: 160px; ">
                    {% else %}
                    <img class="Avatar Avatar--large UserAvatar-inner" src="{{user.avatar}}" style="width: 160px; ">
                    {% endif %}
                    {% if current_user == user %}
                    <div class="Mask UserAvatarEditor-mask Mask-hidden"><div class="Mask-mask Mask-mask--black UserAvatarEditor-maskInner"></div><div class="Mask-content"><i class="fa fa-camera"></i><div class="UserAvatarEditor-maskInnerText">修改我的头像</div></div></div>
                    <form method="post" enctype="multipart/form-data" style="display: none;" action="{{ url_for('profile.uploadAvatar') }}">
                        <input type="file" name="photo" />
                        <button>提交</button>
                    </form>
                    {% endif %}
                    </div>
                </div>
                <div class="profileHeader-content">
                    <div class="profileHeader-contentHead">
                        <h1 class="profileHeader-title">
                            <span class="profileHeader-name">
                                {% if profile and profile.nickname %}
                                {{profile.nickname}}
                                {% else %}
                                {{user.username}}
                                {% endif %}
                            </span>
                        </h1>
                    </div>
                    <div class="profileHeader-contentBody">
                        {% if profile.gender %}
                        <div class="profileHeader-info">
                            <div class="profileHeader-infoItem">
                                <i class="fa fa-mars"></i>
                                <div class="profileHeader-infoValue">
                                    <span>{{profile.gender}}</span>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        <div class="profileHeader-detail" style="display: none;">
                            {% if profile.gender %}
                            <div class="profileHeader-detailItem">
                                <span class="profileHeader-detailLabel">性别</span>
                                <div class="profileHeader-detailValue">
                                    <span>{{ profile.gender }}</span>
                                </div>
                            </div>
                            {% endif %}
                            {% if profile.address %}
                            <div class="profileHeader-detailItem">
                                <span class="profileHeader-detailLabel">居住地</span>
                                <div class="profileHeader-detailValue">
                                    <span>现居{{ profile.address }}</span>
                                </div>
                            </div>
                            {% endif %}
                            {% if profile.discription %}
                            <div class="profileHeader-detailItem">
                                <span class="profileHeader-detailLabel">个人简介</span>
                                <div class="profileHeader-detailValue">
                                    <span>{{profile.discription}}</span>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    
                    <div class="profileHeader-contentFooter">
                        {% if profile.gender or profile.address or profile.discription %}
                        <button class="Button ProfileHeader-expandButton Button--plain" type="button">查看详细资料</button>
                        {% endif %}
                        {% if current_user == user %}
                        <div class="profielButtonGroup profileHeader-buttons">
                            <a href="{{ url_for('profile.editProfile', username=current_user.username) }}"><button class="Button Button--blue" type="button">编辑个人资料</button></a>
                        </div>
                        <div class="clear"></div>
                        {% endif %}
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 模态框 -->
{% if current_user == user %}
<div class="Modal-wrapper" style="display: none;">
    <div class="Modal-backdrop"></div>
    <div class="Modal Modal--default UserAvatarEditor-modal" tabindex="0">
        <div class="Modal-inner">
            <h3 class="Modal-title">编辑头像</h3>
            <div class="Modal-subtitle">调整头像尺寸和位置</div>
            <div class="Modal-content">
                <div>
                    <div class="UserAvatarEditor-container">
                        <!-- <canvas width="240" height="240" style="width: 240px; height: 240px;"></canvas> -->
                    </div>
                    <!-- <div>
                        <i class="fa fa-clone"></i>
                        <input type="range" step="0.01" min="1" max="2" class="RangeInput" value="1">
                        <i class="fa fa-clone fa-2x"></i>
                    </div> -->
                    <div class="ModalButtonGroup ModalButtonGroup--vertical">
                        <button class="Button Button--primary Button--blue" type="button">保存</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="Modal-snackbar Modal-snackbar--collapsed"></div>
        <button class="Button Modal-closeButton Button--plain Modal-closeIcon" aria-label="关闭" type="button"><i class="fa fa-close fa-2x"></i></button>
    </div>
</div>
{% endif %}
<!-- 模态框 -->

{%- endmacro %}