ChiBurger/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextField
from wtforms.validators import DataRequired, Email, Length, Regexp, EqualTo
from wtforms import ValidationError

from ..models import Article


class ArticleForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(message='must add a title'), Length(1,64)])
    body = TextField('Body', validators=[DataRequired()])
    submit = SubmitField()

ChiBurger/main/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, Length, Regexp, EqualTo
from wtforms import ValidationError

from ..models import User

class LoginForm(FlaskForm):
    email = StringField(u'邮箱', validators=[DataRequired(message='a email is needed'), Email()])
    password = PasswordField(u'密码', validators=[DataRequired(message='must enter a password')])
    submit = SubmitField(u'登录')


class SignupForm(FlaskForm):
    username = StringField(u'用户名',validators=[DataRequired(message='a username is needed.'), Length(1,64)])
    email = StringField(u'邮箱',validators=[DataRequired(message='a email is needed'),Length(1,64), Email()])
    password = PasswordField(u'密码', validators=[DataRequired(message='must enter a password'), EqualTo('confirm', message='Password must match')])
    confirm = PasswordField(u'确认密码', validators=[DataRequired()])
    submit = SubmitField(u'注册')

    def validate_username(form, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')

    def vaidate_email(form, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

ChiBurger/__init__.py
# -*- coding:utf-8 -*-

from flask import Flask

from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_uploads import UploadSet, IMAGES, configure_uploads

from config import config

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'main.login'
bootstrap = Bootstrap()
moment = Moment()

# 上传图片
photos = UploadSet('photos', IMAGES)


def create_app(config_name):
    # initialize app
    app = Flask(__name__, instance_relative_config=True)

    # import config
    app.config.from_object(config[config_name])
    app.config.from_pyfile('config.py')

    # 上传图片位置
    import os
    basebir = os.path.abspath(os.path.dirname(__file__))
    app.config['UPLOADED_PHOTOS_DEST'] = basebir + '/static/img'

    # flask extensions initial
    db.init_app(app)
    # toolbar.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)
    configure_uploads(app, photos)

    # import blueprint
    from .admin import admin as admin_blueprint
    from .blog import blog as blog_blueprint
    from .main import main as main_blueprint
    from .profile import profile as profile_blueprint
    from .api_1_0 import api as api_1_0_blueprint

    # register blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')
    app.register_blueprint(blog_blueprint, url_prefix='/blog')
    app.register_blueprint(profile_blueprint, url_prefix='/profile')
    app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')
    app.register_blueprint(main_blueprint)

    return app

ChiBurger/admin/__init__.py
# -*- coding:utf-8 -*-

from flask import Blueprint

# create blueprint: admin
admin = Blueprint('admin', __name__)

# after admin blueprint created, import views
from . import views

ChiBurger/admin/views.py
# -*- coding:utf-8 -*-

from .articles import *
from .categories import *

@admin.route('/')
def index():
    return render_template('admin/index.html')

# 404错误处理
@admin.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

# 500错误处理
@admin.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

ChiBurger/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import  views

ChiBurger/api_1_0/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

ChiBurger/blog/__init__.py
# -*- coding:utf-8 -*-

from flask import Blueprint

# create blueprint:blog
blog = Blueprint('blog', __name__)

# after blueprint created, import views
from . import views

ChiBurger/blog/views.py
# -*- coding:utf-8 -*-

from flask import render_template, url_for, abort, redirect, flash, request, jsonify, Response
from flask_login import login_user, logout_user, login_required, user_login_confirmed

from . import blog
from .. import db, moment
from ..models import Article, User, Category, Comment
from .forms import ArticleForm
from ..utils import get_json_articleInfo, add_category


# blog首页展示所有文章
@blog.route('/')
def index():
    articles = Article.query.order_by(Article.pub_time.desc()).all()
    return render_template('blog/index.html', articles=articles)


# 文章归档
@blog.route('/articles')
def articles():
    articles = Article.query.order_by(Article.pub_time.desc()).all()
    article_num = Article.query.count()
    return render_template('blog/articles.html', 
                            articles=articles, 
                            article_num=article_num)

# 返回指定id的文章
@blog.route('/article/<int:id>')
def article(id):
    article = Article.query.get_or_404(id)
    comments = article.comments.order_by(Comment.pub_time.desc()).all()
    return render_template('blog/article.html', 
                            article=article, 
                            comments=comments)


# 增加新的文章
@blog.route('/article/add', methods=['GET','POST'])
@login_required
def addArticle():
    if request.method == 'POST':
        form = request.form
        title = form.get('title')
        category_name = form.get('category')
        category = add_category(name=category_name)
        body = form.get('editormd-html-code')
        body_md = form.get('editormd-markdown-doc')
        article = Article(title=title, category_id=category.id,
                            body=body, body_md=body_md, user_id=current_user.id)
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('blog.article', id=article.id))
    return render_template('blog/add_article.html')


# 修改指定id的文章
@blog.route('/article/<int:id>/edit', methods=['GET','POST'])
@login_required
def editArticle(id):
    article = Article.query.get_or_404(id)
    if request.method == 'POST':
        form = request.form
        article.title = form.get('title')
        category_name = form.get('category')
        category = add_category(name=category_name)
        article.category_id = category.id
        article.body = form.get('editormd-html-code')
        article.body_md = form.get('editormd-markdown-doc')
        article.mod_time = datetime.utcnow()
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('blog.article', id=id))
    return render_template('blog/edit_article.html', article=article)


# 删除指定id的文章
@blog.route('/article/<int:id>/delete')
@login_required
def deleteArticle(id):
    article = Article.query.get_or_404(id)
    db.session.delete(article)
    db.session.commit()
    return jsonify(status='success')


# 返回所有的文章分类
@blog.route('/categories')
def categories():
    categories = Category.query.all()
    category_num = Category.query.count()
    return render_template('blog/categories.html', 
                            categories=categories,
                            category_num=category_num)

# 返回指定id的文章分类
@blog.route('/category/<int:id>')
def category(id):
    category = Category.query.get_or_404(id)
    articles = category.articles.all()
    article_num = category.articles.count()
    return render_template('blog/category.html', 
                            category=category, 
                            articles=articles, 
                            article_num=article_num)


# 增加新的分类
@blog.route('/category/add', methods=['POST'])
# @login_required
def addCategory():
    form = request.form
    name = form.get('category-name')
    category = Category.query.filter_by(name=name).first()
    if category:
        return jsonify(status='fail', error='The category already exists.')
    category = Category(name=name)
    db.session.add(category)
    db.session.commit()
    return jsonify(status='success')


# 更新指定id的分类信息
@blog.route('/category/<int:id>/edit', methods=['POST'])
@login_required
def editCategory(id):
    category = Category.query.get_or_404(id)
    form = request.form
    category.name = form.get('category-name')
    db.session.add(category)
    db.session.commit()
    return jsonify(status='success')


# 删除指定id的分类
@blog.route('/category/<int:id>/delete', methods=['POST'])
@login_required
def deleteCategory(id):
    category = Category.query.get_or_404(id)
    db.session.delete(category)
    db.session.commit()
    return jsonify(status='success')


# 增加评论
@blog.route('/article/<int:id>/add_comments', methods=['GET', 'POST'])
def addComments(id):
    article = Article.query.get_or_404(id)
    if article:
        comments = article.comments.order_by(Comment.pub_time.desc()).all()
    if request.method == 'POST':
        body = request.form['body']
        user_ip = request.remote_addr
        user_platform = request.user_agent.platform
        user_browser = request.user_agent.browser
        article_id = id
        comment = Comment(body=body, article_id=article_id, user_ip=user_ip,
                            user_platform=user_platform, user_browser=user_browser)
        db.session.add(comment)
        db.session.commit()
        comment_num = article.comments.count()
        return jsonify(id=comment.id,body=comment.body,
                        pub_time=comment.pub_time,
                        article_id=comment.article_id,
                        user_ip=user_ip, 
                        user_platform=user_platform,
                        user_browser=user_browser,
                        comment_num=comment_num)

# 404错误处理
@blog.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

# 500错误处理
@blog.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

ChiBurger/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

ChiBurger/main/views.py
# -*- coding:utf-8 -*-

from flask import render_template, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required
from . import main
from .. import db
from ..models import User, Profile
from .forms import LoginForm, SignupForm

@main.route('/')
def index():
    return redirect(url_for('blog.index'))

@main.route('/login', methods=['GET','POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None:
            if user.vertify_password(form.password.data):
                login_user(user)
                flash("You have logined in successfully!")
                return redirect(request.args.get('next') or url_for('blog.index'))
            flash('Invalid password')
        else:
            flash('Invalid email')
    return render_template('login.html', form=form)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@main.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        user = User(username=form.username.data,
                    password=form.password.data,
                    email=form.email.data)
        profile = Profile(user_id=user.id)
        db.session.add(user)
        db.session.add(profile)
        db.session.commit()
        flash("You have signed up successfully. Now you can login in.")
        return redirect(url_for('main.login'))
    return render_template('signup.html', form=form)

ChiBurger/profile/__init__.py
from flask import Blueprint

profile = Blueprint('profile', __name__)

from . import views

ChiBurger/profile/views.py
# -*- coding:utf-8 -*-

from flask import render_template, url_for, abort, redirect, request, jsonify
from flask_login import login_user, logout_user, login_required, user_login_confirmed, current_user
from flask_uploads import UploadNotAllowed

from . import profile
from .. import db, photos

from ..models import User, Article, Profile, Photo, Message
from ..utils import upload


@profile.route('/')
def index():
    return render_template('profile/home.html')

@profile.route('/<username>')
def home(username):
    user = User.query.filter_by(username=username).first_or_404()
    profile = user.profile
    messages_num = user.messages.count()
    page = request.args.get('page', 1, type=int)
    pagination = user.messages.order_by(Message.pub_time.desc()).paginate(page, per_page=10, error_out=False)
    messages = pagination.items
    return render_template('profile/index.html', user=user, profile=profile,
                            messages=messages, messages_num=messages_num, pagination=pagination)


@profile.route('/<username>/profile-detail')
def getProfile(username):
    user = User.query.filter_by(username=username).first_or_404()
    profile = user.profile
    if profile:
        profile = profile.to_json()
        return jsonify(status='success', profile=profile)
    return jsonify(status='fail', error="There's no profile for current user.")


@profile.route('/<username>/edit', methods=['GET', 'POST'])
@login_required
def editProfile(username):
    user = User.query.filter_by(username=username).first_or_404()
    profile = user.profile

    if request.method == 'POST':
        # import ipdb; ipdb.set_trace()
        if not profile:
            profile = Profile(user_id=user.id)

        # form表单提交
        # form = request.form
        # profile.nickname = form.get('nickname')
        # profile.gender = form.get('gender')
        # profile.address = form.get('address')
        # profile.discription = form.get('discription')

        # 前端Ajax提交
        request_items = request.values.keys()
        # 在模型字段中遍历请求中出现的字段，并且对其赋值
        # 只对修改的字段进行更新，其余未修改的字段不更新
        json_data = {}
        for item in request_items:
            request_value = request.values.get(item)
            setattr(profile, item, request_value)
            json_data[item] = getattr(profile, item)
        db.session.add(profile)
        db.session.commit()
        return jsonify(status='success', data=json_data)
    return render_template('profile/edit_profile.html', user=user, profile=profile)


@profile.route('/upload/avatar', methods=['POST'])
@login_required
def uploadAvatar():
    if request.method == 'POST' and 'photo' in request.files:
        photos = current_user.photos
        if photos is None or photos.filter_by(category='avatar').first() is None:
            avatar = Photo(category='avatar', user_id=current_user.id)
        else:
            avatar = photos.filter_by(category='avatar').first()
        url = upload(request.files['photo'])
        avatar.url = url
        current_user.avatar = url
        db.session.add(avatar)
        db.session.add(current_user)
        db.session.commit()

        return jsonify(status='success', url=url)
    return jsonify(status='fail')


@profile.route('/upload/cover', methods=['POST'])
@login_required
def uploadCover():
    profile = current_user.profile
    if profile is None:
        profile = Profile(user_id=current_user.id)
    if request.method == 'POST' and 'photo' in request.files:
        photos = current_user.photos
        if photos is None or photos.filter_by(category='cover').first() is None:
            cover = Photo(category='cover', user_id=current_user.id)
        else:
            cover = photos.filter_by(category='cover').first()
        url = upload(request.files['photo'])
        cover.url = url
        profile.cover = url
        db.session.add(cover)
        db.session.add(profile)
        db.session.commit()

        return jsonify(status='success', url=url)
    return jsonify(status='fail')


@profile.route('/<username>/add-activity', methods=['POST'])
@login_required
def addActivity(username):
    user = User.query.filter_by(username=username).first_or_404()
    profile = user.profile
    if request.method == 'POST':
        form = request.form
        body = form.get('body')
        message = Message(body=body,user_id=user.id)
        db.session.add(message)
        db.session.commit()
        return jsonify(status='success', message=message.to_json(),
                        user=user.to_json(), profile=profile.to_json())
    return jsonify(status='fail')


# 404错误处理
@profile.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

# 500错误处理
@profile.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

ChiBurger/templates/blog/add_article.html
{% extends 'base.html' %}

{% block title %} 写文章 {% endblock %}

{% block  head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='editormd/css/editormd.min.css') }}">
<script src="{{ url_for('static', filename='editormd/editormd.min.js') }}"></script>
{% endblock %}

{% block content %}
<div id="writeArticle">
    <h3 class="appmsg_edit_item title">写文章</h3>  
    <form id="writeArticleForm" method="post" action="{{ url_for('blog.addArticle') }}">
        <div class="appmsg_edit_item title frm_input_box edui-default with_counter counter_in append count">
            <label for="title" class="tips_global placeholder_tips edui-default" style="display:none">请在这里输入标题</label>
            <input id="title" type="text" placeholder="请在这里输入标题" class="frm_input js_title js_counter js_field edui-default" name="title" max-length="64">
            <em class="frm_input_append frm_counter" style="display: none;">0/64</em>
        </div>
        <div class="appmsg_edit_item author frm_input_box edui-default with_counter counter_in append count">
            <label for="category" class="tips_global placeholder_tips edui-default" style="display:none">请输入文章分类</label>
            <input id="author" type="text" placeholder="请输入文章分类" class="frm_input js_author js_counter js_field edui-default" name="category" max-length="8">
            <em class="frm_input_append frm_counter" style="display: none;">0/8</em>
        </div>
        <div class="editormd" id="editormd">
            <textarea class="editormd-markdown-textarea" name="editormd-markdown-doc"></textarea>
            <textarea class="editormd-html-textarea" name="editormd-html-code"></textarea>
        </div>
        <div class="button" style="text-align: center">
            <button type="submit" name="submit" class="btn btn-success" style="margin: 0 auto">发布文章</button>
        </div>
    </form>
    <br>
</div>

<script type="text/javascript">
    $(function() {
        editormd("editormd", {
        // var addArticleEditor = editormd("editormd", {
            width  : "90%",
            height : 640,
            syncScrolling: "single",
            path   : "/static/editormd/lib/",
            saveHTMLToTextarea : true
        });

        // addArticleEditor.getMarkdown();       // 获取 Markdown 源码
        // addArticleEditor.getHTML();           // 获取 Textarea 保存的 HTML 源码
        // addArticleEditor.getPreviewedHTML();  // 获取预览窗口里的 HTML，在开启 watch 且没有开启 saveHTMLToTextarea 时使用
        // console.log(addArticleEditor.getHTML());
    });
</script>
{% endblock %}

ChiBurger/templates/blog/addarticle.html
{% extends 'base.html' %}

{% block title %}撰写文章{% endblock %}

{% block  head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='editormd/css/editormd.min.css') }}">
<script src="{{ url_for('static', filename='editormd/editormd.min.js') }}"></script>
{% endblock %}

{% block content %}
<div id="writeArticle">
      <h3 class="appmsg_edit_item title">写文章</h1>  
    <form id="writeArticleForm" method="post" action="{{ url_for('blog.addArticle') }}">
        <div class="appmsg_edit_item title frm_input_box edui-default with_counter counter_in append count">
            <label for="title" class="tips_global placeholder_tips edui-default" style="display:none">请在这里输入标题</label>
            <input id="title" type="text" placeholder="请在这里输入标题" class="frm_input js_title js_counter js_field edui-default" name="title" max-length="64">
            <em class="frm_input_append frm_counter" style="display: none;">0/64</em>
        </div>
        <div class="appmsg_edit_item author frm_input_box edui-default with_counter counter_in append count">
            <label for="category" class="tips_global placeholder_tips edui-default" style="display:none">请输入文章分类</label>
            <input id="author" type="text" placeholder="请输入文章分类" class="frm_input js_author js_counter js_field edui-default" name="category" max-length="8">
            <em class="frm_input_append frm_counter" style="display: none;">0/8</em>
        </div>
        <div class="editormd" id="editormd">
            <textarea class="editormd-markdown-textarea" name="editormd-markdown-doc"></textarea>
            <textarea class="editormd-html-textarea" name="editormd-html-code"></textarea>
        </div>
        <!-- <input type="submit" name="submit" value="发布" /> -->
        <div class="button" style="text-align: center">
            <button type="submit" name="submit" class="btn btn-success" style="margin: 0 auto">发布文章</button>
        </div>
    </form>
    <br>
</div>

<script type="text/javascript">
    $(function() {
        editormd("editormd", {
        // var addArticleEditor = editormd("editormd", {
            width  : "90%",
            height : 640,
            syncScrolling: "single",
            path   : "/static/editormd/lib/",
            saveHTMLToTextarea : true
        });

        // addArticleEditor.getMarkdown();       // 获取 Markdown 源码
        // addArticleEditor.getHTML();           // 获取 Textarea 保存的 HTML 源码
        // addArticleEditor.getPreviewedHTML();  // 获取预览窗口里的 HTML，在开启 watch 且没有开启 saveHTMLToTextarea 时使用
        // console.log(addArticleEditor.getHTML());
    });
</script>
{% endblock %}

ChiBurger/templates/blog/article.html
{% extends 'base.html' %}

{% block title %} {{ article.title }} {% endblock %}

{% block content %}

{% import 'blog/article_macro.html' as article_macro %}
<div class="article">
    <header class="article-header">
        <h2 class="article-title" itemprop="name headline">{{ article.title }}</h2>
        {{ article_macro.article_meta(article, moment, current_user) }}
    </header>
    <div class="article-detail article-body">
        {{ article.body | safe }}
    </div>
</div>
<br />

<div class="comment-list">
    {{ article_macro.comment(article, moment, comments) }}
</div>
    
{% endblock %}

{% block scripts %}
{{super()}}
<script src="{{ url_for('static', filename='js/comment.js') }}"></script>
{% endblock %}

ChiBurger/templates/blog/article_macro.html
<!-- 文章信息，包括发表时间、类型、评论数、阅读量等-->
{% macro article_meta(article, moment, current_user) -%}
<div class="article-meta">
    <span class="pub_time">发表于：{{moment(article.pub_time).format('YYYY-M-D HH:mm:ss')}}</span>
    <span class="article-category">&nbsp; | &nbsp;类型：<a href="{{ url_for('blog.category',id=article.category.id) }}">{{article.category.name}}</a></span>
    {% with comment_num = article.comments.count() %}
    {% if comment_num != 0 %}
    <span>&nbsp; | &nbsp;评论：{{ comment_num }}条</span>
    {% else %}
    <span>&nbsp; | &nbsp;暂无评论</span>
    {% endif %}
    {% endwith %}
    <span>&nbsp; | &nbsp;阅读量</span>
    {% if current_user.id == article.user_id %}
    <span>&nbsp; | &nbsp;<a href="{{ url_for('blog.editArticle',id=article.id) }}">编辑</a></span>
    {% endif %}
</div>

{%- endmacro %}


<!-- 评论部分，包括评论框和评论列表 -->
{% macro comment(article, moment, comments) %}
<div class="comments">
    <form id="addComment" action="{{ url_for('blog.addComments', id=article.id) }}" method="post">
        <textarea class="comments" name="body" placeholder="请输入评论"></textarea>
    </form>
    <!-- 注意这个button是由Ajax控制的，因此要放在form表单的外面，
    否则该表单就会被提交两次，一次是form表单提交，一次是Ajax提交。 -->
    <button id="submitComment" type="submit" class="btn btn-info">发表评论</button>
</div>
<div id="articleComment" class="comment-area comment-area-box">
    <div class="comment-tab">
        <ul class="comment-tab-left">
            <li class="current comment-show">全部评论<em class="num" id="allCommentNum">({{ article.comments.count() }})</em></li>
        </ul>
    </div>
    <div class="comment-area-list">
        {% if comments %}
        <div class="comment-list-body">
            {% for comment in comments %}
                <div class="comment-item" id="comment-{{ comment.id }}">
                    <div class="comment-content">
                        <div class="comment-user-avatar">
                            <img src="{{ url_for('static', filename='anonymous.gif') }}">
                        </div>
                        <div class="comment-section">
                            <div class="comment-user-info">
                            {% if comment.user_ip is none or comment.user_platform is none or comment.user_browser is none %}
                                <span>来自 匿名网友</span>
                            {% else %}
                                <span>来自 {{ comment.user_ip }} 的网友 ({{ comment.user_platform }}/{{ comment.user_browser }})</span>
                            {% endif %}
                            </div>
                            <div class="comment-text">
                                <p class="comment">{{ comment.body }}</p>
                            </div>
                            <div class="comment-handle comment-handle-btn">
                                <span class="comment-timestamp">{{ moment(comment.pub_time).fromNow() }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <br />
        {% else %}
            <p class="comment no-comment">暂无评论!</p>
        {% endif %}
        </div>
    </div>
</div>
{%- endmacro %}

ChiBurger/templates/blog/articles.html
{% extends 'base.html' %}

{% block  title %} 文章归档 {% endblock %}

{% block content %}

{% if articles %}
<div class="primary-head">
    <h2 class="normal-head">归档</h2>
    {% if article_num != 0 %}
    <span>共有{{ article_num }}篇文章，继续努力！</span>
    {% else %}
    <span>暂时还没有文章</span>
    {% endif %}
</div>
<div id="article-list">
{% for article in articles %}
    <ul>
        <li style="opacity: 1;display: block;transform: translateY(0px);" class="articles-collapse primary-body"><a href="{{ url_for('blog.article', id=article.id) }}">{{ article.title }}</a></li>
    </ul>
{% endfor %}
</div>
{% else %}
<h1>暂时没有文章</h1>
{% endif %}
{% endblock %}

ChiBurger/templates/blog/base.html
{% extends 'bootstrap/base.html' %}

<!DOCTYPE html>
<html>

{% block title %}{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
{% endblock %}

{% block body %}
    {% block navbar %}
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li role="presentation" class="active"><a href="{{url_for('blog.index')}}">Home</a></li>
              <li role="presentation"><a href="#">Profile</a></li>
              <li role="presentation"><a href="#">Messages</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('blog.login') }}">Logout</a></li>
                {% else %}
                <li><a href="{{ url_for('blog.login') }}">Login</a></li>
              {% endif %}
              <li><a href="{{ url_for('blog.signup') }}">Sign up</a></li>
            </ul>
          </div>
        </div>
    </nav>
    {% endblock %}
    <div class="container">
        <div class="row">
        {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}
</html>

ChiBurger/templates/blog/categories.html
{% extends 'base.html' %}

{% block  title %} 文章分类 {% endblock %}

{% block content %}

{% if categories %}
<div class="primary-head">
    <h2 class="normal-head">分类</h2>
    {% if category_num != 0 %}
    <span>共有{{ category_num }}个分类</span>
    {% else %}
    <span>目前还没有分类！</span>
    {% endif %}
</div>
<div id="category-list">
<ul>
{% for category in categories %}
    <li style="opacity: 1;display: block;transform: translateY(0px);" class="articles-collapse primary-body"><a href="{{ url_for('blog.category', id=category.id) }}">{{ category.name }}<span class="badge">{{ category.articles.count() }}</span></a></li>
{% endfor %}
</ul>
</div>
{% else %}
<h1>暂时没有分类</h1>
{% endif %}
{% endblock %}

ChiBurger/templates/blog/category.html
{% extends 'base.html' %}

{% block  title %} {{ category.name }} {% endblock %}

{% block content %}

<div class="primary-head">
    <h2 class="normal-head">{{ category.name }}</h2>
    {% if article_num != 0 %}
    <span>共有{{ article_num }}篇文章，继续努力！</span>
    {% else %}
    <span>暂时还没有文章</span>
    {% endif %}
</div>
{% if articles %}
<div class="article-list">
<ul>
    {% for article in articles %}
    <li style="opacity: 1;display: block;transform: translateY(0px);" class="articles-collapse primary-body"><a href="{{ url_for('blog.article', id=article.id) }}">{{ article.title }}</a></li>
    {% endfor %}
</ul>
{%endif%}
</div>

{% endblock %}